from django.core.management.base import BaseCommand
from control_dashboard.models import ReportSchedule
from datetime import time

class Command(BaseCommand):
    help = 'Load the report rendition schedule into the database'

    def handle(self, *args, **options):
        reports = [
            {
                'name': 'Branch Consolidated Exceptions Report',
                'report_type': 'Branch Consolidated Exceptions',
                'deadline_description': '15:00 GMT Thursdays (or last working day before a Thursday)',
                'deadline_time': '15:00',
                'deadline_type': 'weekday',
                'deadline_weekday': 'Thursday',
                'responsible_officer_name': 'Roberta Arhin-Andoh',
                'backup_officer_name': 'Paul Dakora',
                'frequency': 'weekly',
            },
            {
                'name': 'Head Office Consolidated Exceptions Report',
                'report_type': 'Head Office Consolidated Exceptions',
                'deadline_description': '15:00 GMT Thursdays (or last working day before a Thursday)',
                'deadline_time': '15:00',
                'deadline_type': 'weekday',
                'deadline_weekday': 'Thursday',
                'responsible_officer_name': 'Christiana Maku Blaboe',
                'backup_officer_name': 'Godfred Aryee',
                'frequency': 'weekly',
            },
            {
                'name': 'Weekly Exceptions Report',
                'report_type': 'Weekly Exceptions',
                'deadline_description': '10:00 GMT Thursday or last working day before a Thursday',
                'deadline_time': '10:00',
                'deadline_type': 'weekday',
                'deadline_weekday': 'Thursday',
                'additional_officers_names': 'All',
                'frequency': 'weekly',
            },
            {
                'name': 'Security Sweep Report',
                'report_type': 'Security Sweep',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Paul Dakora',
                'backup_officer_name': 'Habiba Tamimu',
                'frequency': 'monthly',
            },
            {
                'name': 'Cash Count Report',
                'report_type': 'Cash Count',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Sandra Nana Konadu Ofe',
                'backup_officer_name': 'Noella Afia Konadu Agyapong',
                'frequency': 'monthly',
            },
            {
                'name': 'Cash Imbalance Report',
                'report_type': 'Cash Imbalance',
                'deadline_description': '14:00 GMT 1st working day of the month',
                'deadline_time': '14:00',
                'deadline_type': 'custom',
                'deadline_day': 1,
                'responsible_officer_name': 'Elvis Boafo',
                'backup_officer_name': 'Baffour Kyei Donkor',
                'frequency': 'monthly',
            },
            {
                'name': 'Investigation Schedule',
                'report_type': 'Investigation Schedule',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Christiana Maku Blaboe',
                'backup_officer_name': 'Godfred Aryee',
                'frequency': 'monthly',
            },
            {
                'name': 'Branch GL Proof Report review Consolidation',
                'report_type': 'Branch GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Noella Afia Konadu Agyapong',
                'backup_officer_name': 'Elvis Boafo',
                'frequency': 'monthly',
            },
            {
                'name': 'E-Business GL Proof review',
                'report_type': 'E-Business GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Michael Ofosu Koranteng',
                'backup_officer_name': 'Michael Akye Mensah',
                'frequency': 'monthly',
            },
            {
                'name': 'FINOPs- GL Proof review',
                'report_type': 'FINOPs GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Christiana Maku Blaboe',
                'backup_officer_name': 'Kwabena Aboagye-Abrokwah',
                'frequency': 'monthly',
            },
            {
                'name': 'Finance- GL Proof review',
                'report_type': 'Finance GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Christiana Maku Blaboe',
                'backup_officer_name': 'Kwabena Aboagye-Abrokwah',
                'frequency': 'monthly',
            },
            {
                'name': 'Recovery/Credit GL Proof Review',
                'report_type': 'Recovery/Credit GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Godfred Aryee',
                'backup_officer_name': 'Kwabena Aboagye-Abrokwah',
                'frequency': 'monthly',
            },
            {
                'name': 'TROPs GL Proof Review',
                'report_type': 'TROPs GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Daniel Atsuvi',
                'backup_officer_name': 'Kwabena Aboagye-Abrokwah',
                'frequency': 'monthly',
            },
            {
                'name': 'CMU -Accra GL Proof Review',
                'report_type': 'CMU Accra GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Daniel Atsuvi',
                'backup_officer_name': 'Kwabena Aboagye-Abrokwah',
                'frequency': 'monthly',
            },
            {
                'name': 'CMU- Kumasi GL Proof Review',
                'report_type': 'CMU Kumasi GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Baffour Kyei Donkor',
                'backup_officer_name': 'Paul Dakora',
                'frequency': 'monthly',
            },
            {
                'name': 'CMU-Takoradi GL Proof Review',
                'report_type': 'CMU Takoradi GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Amanda Aba Bonney',
                'backup_officer_name': 'Baffour Kyei Donkor',
                'frequency': 'monthly',
            },
            {
                'name': 'Trade GL Proof Review',
                'report_type': 'Trade GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Kwabena Aboagye-Abrokwah',
                'backup_officer_name': 'Michael Akye Mensah',
                'frequency': 'monthly',
            },
            {
                'name': 'Clearing GL Proof Review',
                'report_type': 'Clearing GL Proof',
                'deadline_description': '14:00 GMT 10th (or last working day before 10th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 10,
                'responsible_officer_name': 'Peter Gyimah Appiah',
                'backup_officer_name': 'Daniel Atsuvi',
                'frequency': 'monthly',
            },
            {
                'name': 'Cost Saved',
                'report_type': 'Cost Saved',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Godfred Aryee',
                'backup_officer_name': 'Peter Gyimah Appiah',
                'frequency': 'monthly',
            },
            {
                'name': 'Debit Reversal',
                'report_type': 'Debit Reversal',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Christiana Maku Blaboe',
                'backup_officer_name': 'Roberta Arhin-Andoh',
                'frequency': 'monthly',
            },
            {
                'name': 'Balance Confirmation',
                'report_type': 'Balance Confirmation',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Peter Gyimah Appiah',
                'backup_officer_name': 'Daniel Atsuvi',
                'frequency': 'monthly',
            },
            {
                'name': 'Statement Verification',
                'report_type': 'Statement Verification',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Roberta Arhin-Andoh',
                'backup_officer_name': 'Kwabena Aboagye-Abrokwah',
                'frequency': 'monthly',
            },
            {
                'name': 'Branch Workplan',
                'report_type': 'Branch Workplan',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Frank Okyere Amoako',
                'backup_officer_name': 'Naomi Ennin',
                'frequency': 'monthly',
            },
            {
                'name': 'Head Office Workplan',
                'report_type': 'Head Office Workplan',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Derrick Selorm Dzeku',
                'backup_officer_name': 'Godfred Aryee',
                'frequency': 'monthly',
            },
            {
                'name': 'Report on Customer Details wrongly Captured and Details not captured in CBA',
                'report_type': 'Customer Details Report',
                'deadline_description': '14:00 GMT 25th (or last working day before 25th)',
                'deadline_time': '14:00',
                'deadline_type': 'monthly_date',
                'deadline_day': 25,
                'responsible_officer_name': 'Stella Adjetey',
                'backup_officer_name': 'Ebenezer Tawiah',
                'frequency': 'monthly',
            },
            {
                'name': 'EOM Presentation (PPT) on Work Done and Key Findings',
                'report_type': 'EOM Presentation',
                'deadline_description': '16:45 GMT Last working day of the month',
                'deadline_time': '16:45',
                'deadline_type': 'custom',
                'deadline_day': 0,
                'additional_officers_names': 'All',
                'frequency': 'monthly',
            },
        ]

        for report_data in reports:
            report, created = ReportSchedule.objects.get_or_create(
                name=report_data['name'],
                defaults={
                    'report_type': report_data['report_type'],
                    'deadline_description': report_data['deadline_description'],
                    'deadline_time': time.fromisoformat(report_data['deadline_time']),
                    'deadline_type': report_data['deadline_type'],
                    'deadline_day': report_data.get('deadline_day'),
                    'deadline_weekday': report_data.get('deadline_weekday', ''),
                    'responsible_officer_name': report_data.get('responsible_officer_name', ''),
                    'backup_officer_name': report_data.get('backup_officer_name', ''),
                    'additional_officers_names': report_data.get('additional_officers_names', ''),
                    'frequency': report_data.get('frequency', 'monthly'),
                    'is_active': True,
                    'is_recurring': True,
                }
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created: {report.name}'))
            else:
                self.stdout.write(self.style.WARNING(f'Already exists: {report.name}'))

        self.stdout.write(self.style.SUCCESS('Report schedule loaded successfully!'))