# Generated by Django 6.0.4 on 2026-07-19 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('one-off', 'One-off')], default='weekly', max_length=50)),
                ('assignment_target', models.CharField(choices=[('all', 'All Users'), ('cc', 'Cluster Control'), ('hc', 'Head Office Control'), ('specific', 'Specific Users')], default='all', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'checklists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exception_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('hc', 'Headoffice Control'), ('cc', 'Cluster Control')], default='member', max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('member', 'Member')], default='member', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='control_dashboard.checklist')),
            ],
            options={
                'db_table': 'checklist_tasks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('textarea', 'Text Area')], default='text', max_length=50)),
                ('data_source', models.CharField(choices=[('manual', 'Manual Input'), ('branches', 'Branches'), ('categories', 'Exception Categories'), ('users', 'Users'), ('database', 'Database')], default='manual', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for dropdown fields')),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='control_dashboard.reporttemplate')),
            ],
            options={
                'db_table': 'template_fields',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='control_dashboard.userprofile'),
        ),
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=200)),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted')], default='submitted', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_submissions', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'report_submissions',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('one-off', 'One Off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='one-off', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('deadline_time', models.TimeField(blank=True, null=True)),
                ('is_assigned_to_all', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_reports', to='control_dashboard.userprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_checklists', to='control_dashboard.userprofile'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklists', to='control_dashboard.userprofile'),
        ),
        migrations.CreateModel(
            name='ChecklistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='control_dashboard.checklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_logs', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'checklist_logs',
                'ordering': ['-log_date'],
                'unique_together': {('checklist', 'user', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='AdHocDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(help_text='Description of the task or report', max_length=255)),
                ('points', models.IntegerField(default=0, help_text='Number of points deducted (0-100)')),
                ('reason', models.TextField(blank=True, help_text='Reason for the deduction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the deduction was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the deduction was last updated')),
                ('created_by', models.ForeignKey(help_text='Supervisor who created the deduction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deductions', to='control_dashboard.userprofile')),
                ('user', models.ForeignKey(help_text='The team member receiving the deduction', on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_deductions', to='control_dashboard.userprofile')),
            ],
            options={
                'verbose_name': 'Ad-Hoc Deduction',
                'verbose_name_plural': 'Ad-Hoc Deductions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='control_das_user_id_d66719_idx'), models.Index(fields=['points'], name='control_das_points_3d6d7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('report_deleted', 'Report Deleted'), ('report_submitted', 'Report Submitted'), ('report_approved', 'Report Approved'), ('report_rejected', 'Report Rejected'), ('checklist_completed', 'Checklist Completed'), ('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_deleted', 'Template Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('email_sent', 'Email Sent'), ('draft_saved', 'Draft Saved'), ('draft_deleted', 'Draft Deleted'), ('deduction_created', 'Deduction Created'), ('deduction_updated', 'Deduction Updated'), ('deduction_deleted', 'Deduction Deleted'), ('score_updated', 'Score Updated')], max_length=50)),
                ('details', models.TextField(blank=True, help_text='Detailed description of the activity', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='control_dashboard.userprofile')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='control_das_user_id_673c7b_idx'), models.Index(fields=['activity_type'], name='control_das_activit_184bca_idx')],
            },
        ),
    ]
