# Generated by Django 6.0.4 on 2026-07-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
