# Generated by Django 6.0.4 on 2026-09-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0002_userprofile_user_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefield',
            name='template',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='template_name',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('report_deleted', 'Report Deleted'), ('report_submitted', 'Report Submitted'), ('report_approved', 'Report Approved'), ('report_rejected', 'Report Rejected'), ('checklist_completed', 'Checklist Completed'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('email_sent', 'Email Sent'), ('draft_saved', 'Draft Saved'), ('draft_deleted', 'Draft Deleted'), ('deduction_created', 'Deduction Created'), ('deduction_updated', 'Deduction Updated'), ('deduction_deleted', 'Deduction Deleted'), ('score_updated', 'Score Updated')], max_length=50),
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.DeleteModel(
            name='TemplateField',
        ),
    ]
