# Generated by Django 6.0.4 on 2026-07-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0003_alter_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('textarea', 'Text Area')], default='text', max_length=50)),
                ('data_source', models.CharField(choices=[('manual', 'Manual Input'), ('branches', 'Branches'), ('categories', 'Exception Categories'), ('users', 'Users'), ('database', 'Database')], default='manual', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for dropdown fields')),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='control_dashboard.reporttemplate')),
            ],
            options={
                'db_table': 'template_fields',
                'ordering': ['order'],
            },
        ),
    ]
