# Generated by Django 6.0.4 on 2026-09-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0003_remove_templatefield_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi-annual', 'Bi-Annual'), ('one-off', 'One-off')], default='weekly', max_length=50),
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one-off', 'One-off')], default='weekly', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('last_submitted', models.DateTimeField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='control_dashboard.report')),
            ],
            options={
                'db_table': 'report_schedules',
                'ordering': ['next_due_date'],
            },
        ),
    ]
