# Generated by Django 6.0.4 on 2026-07-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0003_activitylog_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='due_date',
            new_name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_name',
        ),
        migrations.AddField(
            model_name='report',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='frequency',
            field=models.CharField(choices=[('one-off', 'One Off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='one-off', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='assigned', max_length=50),
        ),
        migrations.AlterModelTable(
            name='report',
            table=None,
        ),
    ]
