# Generated by Django 6.0.4 on 2026-07-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0004_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_status_changed', 'User Status Changed'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('report_deleted', 'Report Deleted'), ('report_assigned', 'Report Assigned'), ('report_completed', 'Report Completed'), ('export', 'Report Export'), ('exception', 'Logged Exception'), ('settings_updated', 'Settings Updated'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
    ]
