# Generated by Django 6.0.4 on 2026-07-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0005_checklist_checklisttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='assignment_target',
            field=models.CharField(choices=[('all', 'All Users'), ('cc', 'Cluster Control'), ('hc', 'Head Office Control'), ('specific', 'Specific Users')], default='all', max_length=50),
        ),
    ]
