# Generated by Django 6.0.4 on 2026-07-12 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0005_alter_report_options_activitylog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_status_changed', 'User Status Changed'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('report_deleted', 'Report Deleted'), ('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_deleted', 'Template Deleted'), ('export', 'Report Export'), ('exception', 'Logged Exception'), ('settings_updated', 'Settings Updated'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated')], max_length=50),
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_created', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('textarea', 'Text Area')], default='text', max_length=50)),
                ('data_source', models.CharField(choices=[('manual', 'Manual Entry'), ('database', 'Database Lookup'), ('options', 'Predefined Options')], default='manual', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, help_text='Comma separated options for dropdown/checkbox')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='control_dashboard.reporttemplate')),
            ],
            options={
                'db_table': 'template_fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='control_dashboard.userprofile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to='control_dashboard.report')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='control_dashboard.reporttemplate')),
            ],
            options={
                'db_table': 'template_assignments',
                'unique_together': {('template', 'report')},
            },
        ),
    ]
