# Generated by Django 6.0.4 on 2026-09-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0005_department_delete_exceptioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, related_name='assigned_checklists', to='control_dashboard.branch'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='assigned_departments',
            field=models.ManyToManyField(blank=True, related_name='assigned_checklists', to='control_dashboard.department'),
        ),
    ]
