# Generated by Django 6.0.4 on 2026-07-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0006_alter_checklist_assignment_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='control_dashboard.checklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_logs', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'checklist_logs',
                'ordering': ['-log_date'],
                'unique_together': {('checklist', 'user', 'log_date')},
            },
        ),
    ]
