# Generated by Django 6.0.4 on 2026-09-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0006_checklist_assigned_branches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='control_dashboard.branch'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='control_dashboard.department'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='assigned_branches',
            field=models.ManyToManyField(blank=True, related_name='checklist_assignments', to='control_dashboard.branch'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='assigned_departments',
            field=models.ManyToManyField(blank=True, related_name='checklist_assignments', to='control_dashboard.department'),
        ),
    ]
