# Generated by Django 6.0.4 on 2026-07-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0007_checklistlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=200)),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted')], default='submitted', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_submissions', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'report_submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
