# Generated by Django 6.0.4 on 2026-09-04 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0007_remove_userprofile_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='data',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='data',
        ),
        migrations.CreateModel(
            name='ReportExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('headers', models.TextField(blank=True, help_text='Comma-separated headers')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_imports', to='control_dashboard.report')),
            ],
            options={
                'db_table': 'report_excel_imports',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExcelRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='control_dashboard.reportexcelimport')),
            ],
            options={
                'db_table': 'report_excel_rows',
                'ordering': ['row_index'],
            },
        ),
        migrations.CreateModel(
            name='ReportExcelCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='control_dashboard.reportexcelrow')),
            ],
            options={
                'db_table': 'report_excel_cells',
                'ordering': ['row__row_index'],
            },
        ),
        migrations.CreateModel(
            name='ReportDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('url', 'URL'), ('textarea', 'Text Area')], default='text', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', to='control_dashboard.report')),
            ],
            options={
                'db_table': 'report_data_fields',
                'ordering': ['order'],
                'unique_together': {('report', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='ReportSubmissionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=255)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('email', 'Email'), ('url', 'URL'), ('textarea', 'Text Area'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], default='text', max_length=50)),
                ('field_label', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='control_dashboard.reportsubmission')),
            ],
            options={
                'db_table': 'report_submission_fields',
                'ordering': ['order'],
                'unique_together': {('submission', 'field_key')},
            },
        ),
    ]
