# Generated by Django 6.0.4 on 2026-07-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0009_branch_exceptioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'No Status'), ('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='', max_length=50),
        ),
    ]
