# Generated by Django 6.0.4 on 2026-07-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0010_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('report_created', 'Report Created'), ('report_updated', 'Report Updated'), ('report_deleted', 'Report Deleted'), ('report_submitted', 'Report Submitted'), ('report_approved', 'Report Approved'), ('report_rejected', 'Report Rejected'), ('checklist_completed', 'Checklist Completed'), ('template_created', 'Template Created'), ('template_updated', 'Template Updated'), ('template_deleted', 'Template Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('email_sent', 'Email Sent'), ('draft_saved', 'Draft Saved'), ('draft_deleted', 'Draft Deleted'), ('deduction_created', 'Deduction Created'), ('deduction_updated', 'Deduction Updated'), ('deduction_deleted', 'Deduction Deleted'), ('score_updated', 'Score Updated')], max_length=50),
        ),
        migrations.CreateModel(
            name='AdHocDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(help_text='Description of the task or report', max_length=255)),
                ('points', models.IntegerField(default=0, help_text='Number of points deducted (0-100)')),
                ('reason', models.TextField(blank=True, help_text='Reason for the deduction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the deduction was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the deduction was last updated')),
                ('created_by', models.ForeignKey(help_text='Supervisor who created the deduction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deductions', to='control_dashboard.userprofile')),
                ('user', models.ForeignKey(help_text='The team member receiving the deduction', on_delete=django.db.models.deletion.CASCADE, related_name='ad_hoc_deductions', to='control_dashboard.userprofile')),
            ],
            options={
                'verbose_name': 'Ad-Hoc Deduction',
                'verbose_name_plural': 'Ad-Hoc Deductions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='control_das_user_id_d66719_idx'), models.Index(fields=['points'], name='control_das_points_3d6d7e_idx')],
            },
        ),
    ]
