# Generated by Django 6.0.4 on 2026-07-18 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0010_alter_draft_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='control_dashboard.checklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_logs', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'checklist_logs',
                'ordering': ['-completion_date'],
                'unique_together': {('checklist', 'user', 'completion_date')},
            },
        ),
    ]
