# Generated by Django 6.0.4 on 2026-07-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_dashboard', '0011_checklistlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the report', max_length=200, unique=True)),
                ('report_type', models.CharField(help_text='Category/Type of report', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the report')),
                ('deadline_type', models.CharField(choices=[('monthly_date', 'Monthly Date'), ('weekday', 'Weekday'), ('custom', 'Custom')], default='monthly_date', max_length=50)),
                ('deadline_day', models.IntegerField(blank=True, help_text='Day of month (1-31) for monthly_date type', null=True)),
                ('deadline_weekday', models.CharField(blank=True, help_text='Day of week for weekday type', max_length=20)),
                ('deadline_time', models.TimeField(help_text='Time when report is due (GMT)')),
                ('deadline_description', models.CharField(blank=True, help_text='Human readable deadline description', max_length=200)),
                ('responsible_officer_name', models.CharField(blank=True, help_text='Name of responsible officer', max_length=200)),
                ('backup_officer_name', models.CharField(blank=True, help_text='Name of backup officer', max_length=200)),
                ('additional_officers_names', models.TextField(blank=True, help_text='Comma separated names of additional officers')),
                ('is_active', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether this is a recurring report')),
                ('frequency', models.CharField(choices=[('one-off', 'One Off'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_officers', models.ManyToManyField(blank=True, help_text='Additional officers assigned to this report', related_name='reports_additional', to='control_dashboard.userprofile')),
                ('backup_officer', models.ForeignKey(blank=True, help_text='Backup officer for this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_backup', to='control_dashboard.userprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to='control_dashboard.userprofile')),
                ('responsible_officer', models.ForeignKey(blank=True, help_text='Primary officer responsible for this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_responsible', to='control_dashboard.userprofile')),
            ],
            options={
                'db_table': 'report_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='pending', max_length=50)),
                ('review_comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='control_dashboard.userprofile')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to='control_dashboard.userprofile')),
                ('report_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='control_dashboard.reportschedule')),
            ],
            options={
                'db_table': 'report_instances',
                'ordering': ['-due_date'],
            },
        ),
    ]
